export type CountrySupport = "full" | "csca" | "special";

export type Country = {
  code: string;
  name: string;
  flag: string;
  region: string;
};

export const countries: Country[] = [
  {
    code: "AFG",
    name: "Afghanistan",
    flag: "🇦🇫",
    region: "Asia",
  },
  {
    code: "ALB",
    name: "Albania",
    flag: "🇦🇱",
    region: "Europe",
  },
  {
    code: "DZA",
    name: "Algeria",
    flag: "🇩🇿",
    region: "Africa",
  },
  {
    code: "AND",
    name: "Andorra",
    flag: "🇦🇩",
    region: "Europe",
  },
  {
    code: "AGO",
    name: "Angola",
    flag: "🇦🇴",
    region: "Africa",
  },
  {
    code: "ATG",
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    region: "Caribbean",
  },
  {
    code: "ARG",
    name: "Argentina",
    flag: "🇦🇷",
    region: "South America",
  },
  {
    code: "ARM",
    name: "Armenia",
    flag: "🇦🇲",
    region: "Asia",
  },
  {
    code: "AUS",
    name: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
  },
  {
    code: "AUT",
    name: "Austria",
    flag: "🇦🇹",
    region: "Europe",
  },
  {
    code: "AZE",
    name: "Azerbaijan",
    flag: "🇦🇿",
    region: "Asia",
  },
  {
    code: "BHS",
    name: "Bahamas",
    flag: "🇧🇸",
    region: "Caribbean",
  },
  {
    code: "BHR",
    name: "Bahrain",
    flag: "🇧🇭",
    region: "Middle East",
  },
  {
    code: "BGD",
    name: "Bangladesh",
    flag: "🇧🇩",
    region: "Asia",
  },
  {
    code: "BRB",
    name: "Barbados",
    flag: "🇧🇧",
    region: "Caribbean",
  },
  {
    code: "BLR",
    name: "Belarus",
    flag: "🇧🇾",
    region: "Europe",
  },
  {
    code: "BEL",
    name: "Belgium",
    flag: "🇧🇪",
    region: "Europe",
  },
  {
    code: "BLZ",
    name: "Belize",
    flag: "🇧🇿",
    region: "Central America",
  },
  {
    code: "BEN",
    name: "Benin",
    flag: "🇧🇯",
    region: "Africa",
  },
  {
    code: "BTN",
    name: "Bhutan",
    flag: "🇧🇹",
    region: "Asia",
  },
  {
    code: "BOL",
    name: "Bolivia",
    flag: "🇧🇴",
    region: "South America",
  },
  {
    code: "BIH",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    region: "Europe",
  },
  {
    code: "BWA",
    name: "Botswana",
    flag: "🇧🇼",
    region: "Africa",
  },
  {
    code: "BRA",
    name: "Brazil",
    flag: "🇧🇷",
    region: "South America",
  },
  {
    code: "BRN",
    name: "Brunei Darussalam",
    flag: "🇧🇳",
    region: "Asia",
  },
  {
    code: "BGR",
    name: "Bulgaria",
    flag: "🇧🇬",
    region: "Europe",
  },
  {
    code: "BFA",
    name: "Burkina Faso",
    flag: "🇧🇫",
    region: "Africa",
  },
  {
    code: "BDI",
    name: "Burundi",
    flag: "🇧🇮",
    region: "Africa",
  },
  {
    code: "CPV",
    name: "Cabo Verde",
    flag: "🇨🇻",
    region: "Africa",
  },
  {
    code: "KHM",
    name: "Cambodia",
    flag: "🇰🇭",
    region: "Asia",
  },
  {
    code: "CMR",
    name: "Cameroon",
    flag: "🇨🇲",
    region: "Africa",
  },
  {
    code: "CAN",
    name: "Canada",
    flag: "🇨🇦",
    region: "North America",
  },
  {
    code: "CAF",
    name: "Central African Republic",
    flag: "🇨🇫",
    region: "Africa",
  },
  {
    code: "TCD",
    name: "Chad",
    flag: "🇹🇩",
    region: "Africa",
  },
  {
    code: "CHL",
    name: "Chile",
    flag: "🇨🇱",
    region: "South America",
  },
  {
    code: "CHN",
    name: "China",
    flag: "🇨🇳",
    region: "Asia",
  },
  {
    code: "COL",
    name: "Colombia",
    flag: "🇨🇴",
    region: "South America",
  },
  {
    code: "COM",
    name: "Comoros",
    flag: "🇰🇲",
    region: "Africa",
  },
  {
    code: "COD",
    name: "Congo, Democratic Republic of the",
    flag: "🇨🇩",
    region: "Africa",
  },
  {
    code: "COG",
    name: "Congo",
    flag: "🇨🇬",
    region: "Africa",
  },
  {
    code: "CRI",
    name: "Costa Rica",
    flag: "🇨🇷",
    region: "Central America",
  },
  {
    code: "CIV",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    region: "Africa",
  },
  {
    code: "HRV",
    name: "Croatia",
    flag: "🇭🇷",
    region: "Europe",
  },
  {
    code: "CUB",
    name: "Cuba",
    flag: "🇨🇺",
    region: "Caribbean",
  },
  {
    code: "CYP",
    name: "Cyprus",
    flag: "🇨🇾",
    region: "Europe",
  },
  {
    code: "CZE",
    name: "Czechia",
    flag: "🇨🇿",
    region: "Europe",
  },
  {
    code: "DNK",
    name: "Denmark",
    flag: "🇩🇰",
    region: "Europe",
  },
  {
    code: "DJI",
    name: "Djibouti",
    flag: "🇩🇯",
    region: "Africa",
  },
  {
    code: "DMA",
    name: "Dominica",
    flag: "🇩🇲",
    region: "Caribbean",
  },
  {
    code: "DOM",
    name: "Dominican Republic",
    flag: "🇩🇴",
    region: "Caribbean",
  },
  {
    code: "ECU",
    name: "Ecuador",
    flag: "🇪🇨",
    region: "South America",
  },
  {
    code: "EGY",
    name: "Egypt",
    flag: "🇪🇬",
    region: "Africa",
  },
  {
    code: "SLV",
    name: "El Salvador",
    flag: "🇸🇻",
    region: "Central America",
  },
  {
    code: "GNQ",
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    region: "Africa",
  },
  {
    code: "ERI",
    name: "Eritrea",
    flag: "🇪🇷",
    region: "Africa",
  },
  {
    code: "EST",
    name: "Estonia",
    flag: "🇪🇪",
    region: "Europe",
  },
  {
    code: "SWZ",
    name: "Eswatini",
    flag: "🇸🇿",
    region: "Africa",
  },
  {
    code: "ETH",
    name: "Ethiopia",
    flag: "🇪🇹",
    region: "Africa",
  },
  {
    code: "FJI",
    name: "Fiji",
    flag: "🇫🇯",
    region: "Oceania",
  },
  {
    code: "FIN",
    name: "Finland",
    flag: "🇫🇮",
    region: "Europe",
  },
  {
    code: "FRA",
    name: "France",
    flag: "🇫🇷",
    region: "Europe",
  },
  {
    code: "GAB",
    name: "Gabon",
    flag: "🇬🇦",
    region: "Africa",
  },
  {
    code: "GMB",
    name: "Gambia",
    flag: "🇬🇲",
    region: "Africa",
  },
  {
    code: "GEO",
    name: "Georgia",
    flag: "🇬🇪",
    region: "Asia",
  },
  {
    code: "DEU",
    name: "Germany",
    flag: "🇩🇪",
    region: "Europe",
  },
  {
    code: "GHA",
    name: "Ghana",
    flag: "🇬🇭",
    region: "Africa",
  },
  {
    code: "GRC",
    name: "Greece",
    flag: "🇬🇷",
    region: "Europe",
  },
  {
    code: "GRD",
    name: "Grenada",
    flag: "🇬🇩",
    region: "Caribbean",
  },
  {
    code: "GTM",
    name: "Guatemala",
    flag: "🇬🇹",
    region: "Central America",
  },
  {
    code: "GIN",
    name: "Guinea",
    flag: "🇬🇳",
    region: "Africa",
  },
  {
    code: "GNB",
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    region: "Africa",
  },
  {
    code: "GUY",
    name: "Guyana",
    flag: "🇬🇾",
    region: "South America",
  },
  {
    code: "HTI",
    name: "Haiti",
    flag: "🇭🇹",
    region: "Caribbean",
  },
  {
    code: "HND",
    name: "Honduras",
    flag: "🇭🇳",
    region: "Central America",
  },
  {
    code: "HUN",
    name: "Hungary",
    flag: "🇭🇺",
    region: "Europe",
  },
  {
    code: "ISL",
    name: "Iceland",
    flag: "🇮🇸",
    region: "Europe",
  },
  {
    code: "IND",
    name: "India",
    flag: "🇮🇳",
    region: "Asia",
  },
  {
    code: "IDN",
    name: "Indonesia",
    flag: "🇮🇩",
    region: "Asia",
  },
  {
    code: "IRN",
    name: "Iran",
    flag: "🇮🇷",
    region: "Middle East",
  },
  {
    code: "IRQ",
    name: "Iraq",
    flag: "🇮🇶",
    region: "Middle East",
  },
  {
    code: "IRL",
    name: "Ireland",
    flag: "🇮🇪",
    region: "Europe",
  },
  {
    code: "ISR",
    name: "Israel",
    flag: "🇮🇱",
    region: "Middle East",
  },
  {
    code: "ITA",
    name: "Italy",
    flag: "🇮🇹",
    region: "Europe",
  },
  {
    code: "JAM",
    name: "Jamaica",
    flag: "🇯🇲",
    region: "Caribbean",
  },
  {
    code: "JPN",
    name: "Japan",
    flag: "🇯🇵",
    region: "Asia",
  },
  {
    code: "JOR",
    name: "Jordan",
    flag: "🇯🇴",
    region: "Middle East",
  },
  {
    code: "KAZ",
    name: "Kazakhstan",
    flag: "🇰🇿",
    region: "Asia",
  },
  {
    code: "KEN",
    name: "Kenya",
    flag: "🇰🇪",
    region: "Africa",
  },
  {
    code: "KIR",
    name: "Kiribati",
    flag: "🇰🇮",
    region: "Oceania",
  },
  {
    code: "PRK",
    name: "Korea, Democratic People's Republic of",
    flag: "🇰🇵",
    region: "Asia",
  },
  {
    code: "KOR",
    name: "Korea, Republic of",
    flag: "🇰🇷",
    region: "Asia",
  },
  {
    code: "KWT",
    name: "Kuwait",
    flag: "🇰🇼",
    region: "Middle East",
  },
  {
    code: "KGZ",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    region: "Asia",
  },
  {
    code: "LAO",
    name: "Lao People's Democratic Republic",
    flag: "🇱🇦",
    region: "Asia",
  },
  {
    code: "LVA",
    name: "Latvia",
    flag: "🇱🇻",
    region: "Europe",
  },
  {
    code: "LBN",
    name: "Lebanon",
    flag: "🇱🇧",
    region: "Middle East",
  },
  {
    code: "LSO",
    name: "Lesotho",
    flag: "🇱🇸",
    region: "Africa",
  },
  {
    code: "LBR",
    name: "Liberia",
    flag: "🇱🇷",
    region: "Africa",
  },
  {
    code: "LBY",
    name: "Libya",
    flag: "🇱🇾",
    region: "Africa",
  },
  {
    code: "LIE",
    name: "Liechtenstein",
    flag: "🇱🇮",
    region: "Europe",
  },
  {
    code: "LTU",
    name: "Lithuania",
    flag: "🇱🇹",
    region: "Europe",
  },
  {
    code: "LUX",
    name: "Luxembourg",
    flag: "🇱🇺",
    region: "Europe",
  },
  {
    code: "MDG",
    name: "Madagascar",
    flag: "🇲🇬",
    region: "Africa",
  },
  {
    code: "MWI",
    name: "Malawi",
    flag: "🇲🇼",
    region: "Africa",
  },
  {
    code: "MYS",
    name: "Malaysia",
    flag: "🇲🇾",
    region: "Asia",
  },
  {
    code: "MDV",
    name: "Maldives",
    flag: "🇲🇻",
    region: "Asia",
  },
  {
    code: "MLI",
    name: "Mali",
    flag: "🇲🇱",
    region: "Africa",
  },
  {
    code: "MLT",
    name: "Malta",
    flag: "🇲🇹",
    region: "Europe",
  },
  {
    code: "MHL",
    name: "Marshall Islands",
    flag: "🇲🇭",
    region: "Oceania",
  },
  {
    code: "MRT",
    name: "Mauritania",
    flag: "🇲🇷",
    region: "Africa",
  },
  {
    code: "MUS",
    name: "Mauritius",
    flag: "🇲🇺",
    region: "Africa",
  },
  {
    code: "MEX",
    name: "Mexico",
    flag: "🇲🇽",
    region: "North America",
  },
  {
    code: "FSM",
    name: "Micronesia",
    flag: "🇫🇲",
    region: "Oceania",
  },
  {
    code: "MDA",
    name: "Moldova",
    flag: "🇲🇩",
    region: "Europe",
  },
  {
    code: "MCO",
    name: "Monaco",
    flag: "🇲🇨",
    region: "Europe",
  },
  {
    code: "MNG",
    name: "Mongolia",
    flag: "🇲🇳",
    region: "Asia",
  },
  {
    code: "MNE",
    name: "Montenegro",
    flag: "🇲🇪",
    region: "Europe",
  },
  {
    code: "MAR",
    name: "Morocco",
    flag: "🇲🇦",
    region: "Africa",
  },
  {
    code: "MOZ",
    name: "Mozambique",
    flag: "🇲🇿",
    region: "Africa",
  },
  {
    code: "MMR",
    name: "Myanmar",
    flag: "🇲🇲",
    region: "Asia",
  },
  {
    code: "NAM",
    name: "Namibia",
    flag: "🇳🇦",
    region: "Africa",
  },
  {
    code: "NRU",
    name: "Nauru",
    flag: "🇳🇷",
    region: "Oceania",
  },
  {
    code: "NPL",
    name: "Nepal",
    flag: "🇳🇵",
    region: "Asia",
  },
  {
    code: "NLD",
    name: "Netherlands",
    flag: "🇳🇱",
    region: "Europe",
  },
  {
    code: "NZL",
    name: "New Zealand",
    flag: "🇳🇿",
    region: "Oceania",
  },
  {
    code: "NIC",
    name: "Nicaragua",
    flag: "🇳🇮",
    region: "Central America",
  },
  {
    code: "NER",
    name: "Niger",
    flag: "🇳🇪",
    region: "Africa",
  },
  {
    code: "NGA",
    name: "Nigeria",
    flag: "🇳🇬",
    region: "Africa",
  },
  {
    code: "MKD",
    name: "North Macedonia",
    flag: "🇲🇰",
    region: "Europe",
  },
  {
    code: "NOR",
    name: "Norway",
    flag: "🇳🇴",
    region: "Europe",
  },
  {
    code: "OMN",
    name: "Oman",
    flag: "🇴🇲",
    region: "Middle East",
  },
  {
    code: "PAK",
    name: "Pakistan",
    flag: "🇵🇰",
    region: "Asia",
  },
  {
    code: "PLW",
    name: "Palau",
    flag: "🇵🇼",
    region: "Oceania",
  },
  {
    code: "PAN",
    name: "Panama",
    flag: "🇵🇦",
    region: "Central America",
  },
  {
    code: "PNG",
    name: "Papua New Guinea",
    flag: "🇵🇬",
    region: "Oceania",
  },
  {
    code: "PRY",
    name: "Paraguay",
    flag: "🇵🇾",
    region: "South America",
  },
  {
    code: "PER",
    name: "Peru",
    flag: "🇵🇪",
    region: "South America",
  },
  {
    code: "PHL",
    name: "Philippines",
    flag: "🇵🇭",
    region: "Asia",
  },
  {
    code: "POL",
    name: "Poland",
    flag: "🇵🇱",
    region: "Europe",
  },
  {
    code: "PRT",
    name: "Portugal",
    flag: "🇵🇹",
    region: "Europe",
  },
  {
    code: "QAT",
    name: "Qatar",
    flag: "🇶🇦",
    region: "Middle East",
  },
  {
    code: "ROU",
    name: "Romania",
    flag: "🇷🇴",
    region: "Europe",
  },
  {
    code: "RUS",
    name: "Russian Federation",
    flag: "🇷🇺",
    region: "Europe",
  },
  {
    code: "RWA",
    name: "Rwanda",
    flag: "🇷🇼",
    region: "Africa",
  },
  {
    code: "KNA",
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    region: "Caribbean",
  },
  {
    code: "LCA",
    name: "Saint Lucia",
    flag: "🇱🇨",
    region: "Caribbean",
  },
  {
    code: "VCT",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    region: "Caribbean",
  },
  {
    code: "WSM",
    name: "Samoa",
    flag: "🇼🇸",
    region: "Oceania",
  },
  {
    code: "SMR",
    name: "San Marino",
    flag: "🇸🇲",
    region: "Europe",
  },
  {
    code: "STP",
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    region: "Africa",
  },
  {
    code: "SAU",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    region: "Middle East",
  },
  {
    code: "SEN",
    name: "Senegal",
    flag: "🇸🇳",
    region: "Africa",
  },
  {
    code: "SRB",
    name: "Serbia",
    flag: "🇷🇸",
    region: "Europe",
  },
  {
    code: "SYC",
    name: "Seychelles",
    flag: "🇸🇨",
    region: "Africa",
  },
  {
    code: "SLE",
    name: "Sierra Leone",
    flag: "🇸🇱",
    region: "Africa",
  },
  {
    code: "SGP",
    name: "Singapore",
    flag: "🇸🇬",
    region: "Asia",
  },
  {
    code: "SVK",
    name: "Slovakia",
    flag: "🇸🇰",
    region: "Europe",
  },
  {
    code: "SVN",
    name: "Slovenia",
    flag: "🇸🇮",
    region: "Europe",
  },
  {
    code: "SLB",
    name: "Solomon Islands",
    flag: "🇸🇧",
    region: "Oceania",
  },
  {
    code: "SOM",
    name: "Somalia",
    flag: "🇸🇴",
    region: "Africa",
  },
  {
    code: "ZAF",
    name: "South Africa",
    flag: "🇿🇦",
    region: "Africa",
  },
  {
    code: "SSD",
    name: "South Sudan",
    flag: "🇸🇸",
    region: "Africa",
  },
  {
    code: "ESP",
    name: "Spain",
    flag: "🇪🇸",
    region: "Europe",
  },
  {
    code: "LKA",
    name: "Sri Lanka",
    flag: "🇱🇰",
    region: "Asia",
  },
  {
    code: "SDN",
    name: "Sudan",
    flag: "🇸🇩",
    region: "Africa",
  },
  {
    code: "SUR",
    name: "Suriname",
    flag: "🇸🇷",
    region: "South America",
  },
  {
    code: "SWE",
    name: "Sweden",
    flag: "🇸🇪",
    region: "Europe",
  },
  {
    code: "CHE",
    name: "Switzerland",
    flag: "🇨🇭",
    region: "Europe",
  },
  {
    code: "SYR",
    name: "Syrian Arab Republic",
    flag: "🇸🇾",
    region: "Middle East",
  },
  {
    code: "TJK",
    name: "Tajikistan",
    flag: "🇹🇯",
    region: "Asia",
  },
  {
    code: "TZA",
    name: "Tanzania",
    flag: "🇹🇿",
    region: "Africa",
  },
  {
    code: "THA",
    name: "Thailand",
    flag: "🇹🇭",
    region: "Asia",
  },
  {
    code: "TLS",
    name: "Timor-Leste",
    flag: "🇹🇱",
    region: "Asia",
  },
  {
    code: "TGO",
    name: "Togo",
    flag: "🇹🇬",
    region: "Africa",
  },
  {
    code: "TON",
    name: "Tonga",
    flag: "🇹🇴",
    region: "Oceania",
  },
  {
    code: "TTO",
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    region: "Caribbean",
  },
  {
    code: "TUN",
    name: "Tunisia",
    flag: "🇹🇳",
    region: "Africa",
  },
  {
    code: "TUR",
    name: "Türkiye",
    flag: "🇹🇷",
    region: "Europe",
  },
  {
    code: "TKM",
    name: "Turkmenistan",
    flag: "🇹🇲",
    region: "Asia",
  },
  {
    code: "TUV",
    name: "Tuvalu",
    flag: "🇹🇻",
    region: "Oceania",
  },
  {
    code: "UGA",
    name: "Uganda",
    flag: "🇺🇬",
    region: "Africa",
  },
  {
    code: "UKR",
    name: "Ukraine",
    flag: "🇺🇦",
    region: "Europe",
  },
  {
    code: "ARE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    region: "Middle East",
  },
  {
    code: "GBR",
    name: "United Kingdom",
    flag: "🇬🇧",
    region: "Europe",
  },
  {
    code: "USA",
    name: "United States of America",
    flag: "🇺🇸",
    region: "North America",
  },
  {
    code: "URY",
    name: "Uruguay",
    flag: "🇺🇾",
    region: "South America",
  },
  {
    code: "UZB",
    name: "Uzbekistan",
    flag: "🇺🇿",
    region: "Asia",
  },
  {
    code: "VUT",
    name: "Vanuatu",
    flag: "🇻🇺",
    region: "Oceania",
  },
  {
    code: "VEN",
    name: "Venezuela",
    flag: "🇻🇪",
    region: "South America",
  },
  {
    code: "VNM",
    name: "Viet Nam",
    flag: "🇻🇳",
    region: "Asia",
  },
  {
    code: "YEM",
    name: "Yemen",
    flag: "🇾🇪",
    region: "Middle East",
  },
  {
    code: "ZMB",
    name: "Zambia",
    flag: "🇿🇲",
    region: "Africa",
  },
  {
    code: "ZWE",
    name: "Zimbabwe",
    flag: "🇿🇼",
    region: "Africa",
  },
];

export const getCountryByCode = (code: string): Country | undefined =>
  countries.find((country) => country.code === code);

export const searchCountries = (query: string): Country[] => {
  const lowerQuery = query.toLowerCase();
  return countries.filter(
    (country) =>
      country.name.toLowerCase().includes(lowerQuery) ||
      country.code.toLowerCase().includes(lowerQuery) ||
      country.region.toLowerCase().includes(lowerQuery)
  );
};
