export type CountrySupport = "full" | "csca" | "special";

export type Country = {
  code: string;
  name: string;
  flag: string;
  region: string;
  support: CountrySupport;
};

export const countries: Country[] = [
  // Full Support (Both DSC and CSCA)
  {
    code: "AE",
    name: "United Arab Emirates",
    flag: "🇦🇪",
    region: "Middle East",
    support: "full",
  },
  {
    code: "AR",
    name: "Argentina",
    flag: "🇦🇷",
    region: "South America",
    support: "full",
  },
  {
    code: "AT",
    name: "Austria",
    flag: "🇦🇹",
    region: "Europe",
    support: "full",
  },
  {
    code: "AU",
    name: "Australia",
    flag: "🇦🇺",
    region: "Oceania",
    support: "full",
  },
  {
    code: "BG",
    name: "Bulgaria",
    flag: "🇧🇬",
    region: "Europe",
    support: "full",
  },
  {
    code: "BH",
    name: "Bahrain",
    flag: "🇧🇭",
    region: "Middle East",
    support: "full",
  },
  { code: "BJ", name: "Benin", flag: "🇧🇯", region: "Africa", support: "full" },
  {
    code: "BR",
    name: "Brazil",
    flag: "🇧🇷",
    region: "South America",
    support: "full",
  },
  {
    code: "BZ",
    name: "Belize",
    flag: "🇧🇿",
    region: "Central America",
    support: "full",
  },
  {
    code: "CA",
    name: "Canada",
    flag: "🇨🇦",
    region: "North America",
    support: "full",
  },
  {
    code: "CH",
    name: "Switzerland",
    flag: "🇨🇭",
    region: "Europe",
    support: "full",
  },
  {
    code: "CM",
    name: "Cameroon",
    flag: "🇨🇲",
    region: "Africa",
    support: "full",
  },
  { code: "CN", name: "China", flag: "🇨🇳", region: "Asia", support: "full" },
  {
    code: "CO",
    name: "Colombia",
    flag: "🇨🇴",
    region: "South America",
    support: "full",
  },
  {
    code: "CZ",
    name: "Czech Republic",
    flag: "🇨🇿",
    region: "Europe",
    support: "full",
  },
  {
    code: "DE",
    name: "Germany",
    flag: "🇩🇪",
    region: "Europe",
    support: "full",
  },
  { code: "ES", name: "Spain", flag: "🇪🇸", region: "Europe", support: "full" },
  {
    code: "EU",
    name: "European Union",
    flag: "🇪🇺",
    region: "Europe",
    support: "full",
  },
  {
    code: "FI",
    name: "Finland",
    flag: "🇫🇮",
    region: "Europe",
    support: "full",
  },
  { code: "FR", name: "France", flag: "🇫🇷", region: "Europe", support: "full" },
  {
    code: "GB",
    name: "United Kingdom",
    flag: "🇬🇧",
    region: "Europe",
    support: "full",
  },
  {
    code: "HU",
    name: "Hungary",
    flag: "🇭🇺",
    region: "Europe",
    support: "full",
  },
  {
    code: "ID",
    name: "Indonesia",
    flag: "🇮🇩",
    region: "Asia",
    support: "full",
  },
  {
    code: "IE",
    name: "Ireland",
    flag: "🇮🇪",
    region: "Europe",
    support: "full",
  },
  {
    code: "IQ",
    name: "Iraq",
    flag: "🇮🇶",
    region: "Middle East",
    support: "full",
  },
  {
    code: "IR",
    name: "Iran",
    flag: "🇮🇷",
    region: "Middle East",
    support: "full",
  },
  {
    code: "IS",
    name: "Iceland",
    flag: "🇮🇸",
    region: "Europe",
    support: "full",
  },
  { code: "IT", name: "Italy", flag: "🇮🇹", region: "Europe", support: "full" },
  { code: "JP", name: "Japan", flag: "🇯🇵", region: "Asia", support: "full" },
  {
    code: "KR",
    name: "South Korea",
    flag: "🇰🇷",
    region: "Asia",
    support: "full",
  },
  {
    code: "LU",
    name: "Luxembourg",
    flag: "🇱🇺",
    region: "Europe",
    support: "full",
  },
  {
    code: "MA",
    name: "Morocco",
    flag: "🇲🇦",
    region: "Africa",
    support: "full",
  },
  {
    code: "MD",
    name: "Moldova",
    flag: "🇲🇩",
    region: "Europe",
    support: "full",
  },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", region: "Asia", support: "full" },
  {
    code: "MX",
    name: "Mexico",
    flag: "🇲🇽",
    region: "North America",
    support: "full",
  },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", region: "Asia", support: "full" },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    region: "Africa",
    support: "full",
  },
  { code: "NO", name: "Norway", flag: "🇳🇴", region: "Europe", support: "full" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", region: "Asia", support: "full" },
  {
    code: "NZ",
    name: "New Zealand",
    flag: "🇳🇿",
    region: "Oceania",
    support: "full",
  },
  {
    code: "PA",
    name: "Panama",
    flag: "🇵🇦",
    region: "Central America",
    support: "full",
  },
  {
    code: "QA",
    name: "Qatar",
    flag: "🇶🇦",
    region: "Middle East",
    support: "full",
  },
  {
    code: "RO",
    name: "Romania",
    flag: "🇷🇴",
    region: "Europe",
    support: "full",
  },
  { code: "RW", name: "Rwanda", flag: "🇷🇼", region: "Africa", support: "full" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", region: "Europe", support: "full" },
  {
    code: "SG",
    name: "Singapore",
    flag: "🇸🇬",
    region: "Asia",
    support: "full",
  },
  {
    code: "SK",
    name: "Slovakia",
    flag: "🇸🇰",
    region: "Europe",
    support: "full",
  },
  { code: "TH", name: "Thailand", flag: "🇹🇭", region: "Asia", support: "full" },
  {
    code: "TM",
    name: "Turkmenistan",
    flag: "🇹🇲",
    region: "Asia",
    support: "full",
  },
  {
    code: "TZ",
    name: "Tanzania",
    flag: "🇹🇿",
    region: "Africa",
    support: "full",
  },
  {
    code: "UA",
    name: "Ukraine",
    flag: "🇺🇦",
    region: "Europe",
    support: "full",
  },
  {
    code: "US",
    name: "United States",
    flag: "🇺🇸",
    region: "North America",
    support: "full",
  },
  {
    code: "UZ",
    name: "Uzbekistan",
    flag: "🇺🇿",
    region: "Asia",
    support: "full",
  },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", region: "Asia", support: "full" },

  // CSCA Support Only
  {
    code: "AD",
    name: "Andorra",
    flag: "🇦🇩",
    region: "Europe",
    support: "csca",
  },
  {
    code: "AG",
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    region: "Caribbean",
    support: "csca",
  },
  {
    code: "AL",
    name: "Albania",
    flag: "🇦🇱",
    region: "Europe",
    support: "csca",
  },
  { code: "AM", name: "Armenia", flag: "🇦🇲", region: "Asia", support: "csca" },
  {
    code: "AZ",
    name: "Azerbaijan",
    flag: "🇦🇿",
    region: "Asia",
    support: "csca",
  },
  {
    code: "BA",
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    region: "Europe",
    support: "csca",
  },
  {
    code: "BB",
    name: "Barbados",
    flag: "🇧🇧",
    region: "Caribbean",
    support: "csca",
  },
  {
    code: "BD",
    name: "Bangladesh",
    flag: "🇧🇩",
    region: "Asia",
    support: "csca",
  },
  {
    code: "BE",
    name: "Belgium",
    flag: "🇧🇪",
    region: "Europe",
    support: "csca",
  },
  {
    code: "BS",
    name: "Bahamas",
    flag: "🇧🇸",
    region: "Caribbean",
    support: "csca",
  },
  {
    code: "BW",
    name: "Botswana",
    flag: "🇧🇼",
    region: "Africa",
    support: "csca",
  },
  {
    code: "BY",
    name: "Belarus",
    flag: "🇧🇾",
    region: "Europe",
    support: "csca",
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    region: "Africa",
    support: "csca",
  },
  {
    code: "CL",
    name: "Chile",
    flag: "🇨🇱",
    region: "South America",
    support: "csca",
  },
  {
    code: "CR",
    name: "Costa Rica",
    flag: "🇨🇷",
    region: "Central America",
    support: "csca",
  },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", region: "Europe", support: "csca" },
  {
    code: "DK",
    name: "Denmark",
    flag: "🇩🇰",
    region: "Europe",
    support: "csca",
  },
  {
    code: "DM",
    name: "Dominica",
    flag: "🇩🇲",
    region: "Caribbean",
    support: "csca",
  },
  {
    code: "DZ",
    name: "Algeria",
    flag: "🇩🇿",
    region: "Africa",
    support: "csca",
  },
  {
    code: "EC",
    name: "Ecuador",
    flag: "🇪🇨",
    region: "South America",
    support: "csca",
  },
  {
    code: "EE",
    name: "Estonia",
    flag: "🇪🇪",
    region: "Europe",
    support: "csca",
  },
  { code: "GE", name: "Georgia", flag: "🇬🇪", region: "Asia", support: "csca" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", region: "Africa", support: "csca" },
  { code: "GM", name: "Gambia", flag: "🇬🇲", region: "Africa", support: "csca" },
  { code: "GR", name: "Greece", flag: "🇬🇷", region: "Europe", support: "csca" },
  {
    code: "HR",
    name: "Croatia",
    flag: "🇭🇷",
    region: "Europe",
    support: "csca",
  },
  {
    code: "IL",
    name: "Israel",
    flag: "🇮🇱",
    region: "Middle East",
    support: "csca",
  },
  { code: "IN", name: "India", flag: "🇮🇳", region: "Asia", support: "csca" },
  {
    code: "JM",
    name: "Jamaica",
    flag: "🇯🇲",
    region: "Caribbean",
    support: "csca",
  },
  { code: "KE", name: "Kenya", flag: "🇰🇪", region: "Africa", support: "csca" },
  {
    code: "KN",
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    region: "Caribbean",
    support: "csca",
  },
  {
    code: "KP",
    name: "North Korea",
    flag: "🇰🇵",
    region: "Asia",
    support: "csca",
  },
  { code: "KS", name: "Kosovo", flag: "🇽🇰", region: "Europe", support: "csca" },
  {
    code: "KW",
    name: "Kuwait",
    flag: "🇰🇼",
    region: "Middle East",
    support: "csca",
  },
  {
    code: "KZ",
    name: "Kazakhstan",
    flag: "🇰🇿",
    region: "Asia",
    support: "csca",
  },
  {
    code: "LB",
    name: "Lebanon",
    flag: "🇱🇧",
    region: "Middle East",
    support: "csca",
  },
  {
    code: "LI",
    name: "Liechtenstein",
    flag: "🇱🇮",
    region: "Europe",
    support: "csca",
  },
  {
    code: "LT",
    name: "Lithuania",
    flag: "🇱🇹",
    region: "Europe",
    support: "csca",
  },
  { code: "LV", name: "Latvia", flag: "🇱🇻", region: "Europe", support: "csca" },
  { code: "MC", name: "Monaco", flag: "🇲🇨", region: "Europe", support: "csca" },
  {
    code: "ME",
    name: "Montenegro",
    flag: "🇲🇪",
    region: "Europe",
    support: "csca",
  },
  {
    code: "MK",
    name: "North Macedonia",
    flag: "🇲🇰",
    region: "Europe",
    support: "csca",
  },
  { code: "MT", name: "Malta", flag: "🇲🇹", region: "Europe", support: "csca" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", region: "Asia", support: "csca" },
  {
    code: "NL",
    name: "Netherlands",
    flag: "🇳🇱",
    region: "Europe",
    support: "csca",
  },
  {
    code: "OM",
    name: "Oman",
    flag: "🇴🇲",
    region: "Middle East",
    support: "csca",
  },
  {
    code: "PE",
    name: "Peru",
    flag: "🇵🇪",
    region: "South America",
    support: "csca",
  },
  {
    code: "PH",
    name: "Philippines",
    flag: "🇵🇭",
    region: "Asia",
    support: "csca",
  },
  { code: "PL", name: "Poland", flag: "🇵🇱", region: "Europe", support: "csca" },
  {
    code: "PS",
    name: "Palestine",
    flag: "🇵🇸",
    region: "Middle East",
    support: "csca",
  },
  {
    code: "PT",
    name: "Portugal",
    flag: "🇵🇹",
    region: "Europe",
    support: "csca",
  },
  {
    code: "PY",
    name: "Paraguay",
    flag: "🇵🇾",
    region: "South America",
    support: "csca",
  },
  { code: "RS", name: "Serbia", flag: "🇷🇸", region: "Europe", support: "csca" },
  {
    code: "RU",
    name: "Russia",
    flag: "🇷🇺",
    region: "Asia/Europe",
    support: "csca",
  },
  {
    code: "SA",
    name: "Saudi Arabia",
    flag: "🇸🇦",
    region: "Middle East",
    support: "csca",
  },
  {
    code: "SC",
    name: "Seychelles",
    flag: "🇸🇨",
    region: "Africa",
    support: "csca",
  },
  {
    code: "SI",
    name: "Slovenia",
    flag: "🇸🇮",
    region: "Europe",
    support: "csca",
  },
  {
    code: "SM",
    name: "San Marino",
    flag: "🇸🇲",
    region: "Europe",
    support: "csca",
  },
  {
    code: "SN",
    name: "Senegal",
    flag: "🇸🇳",
    region: "Africa",
    support: "csca",
  },
  {
    code: "SY",
    name: "Syria",
    flag: "🇸🇾",
    region: "Middle East",
    support: "csca",
  },
  {
    code: "TJ",
    name: "Tajikistan",
    flag: "🇹🇯",
    region: "Asia",
    support: "csca",
  },
  {
    code: "TL",
    name: "Timor-Leste",
    flag: "🇹🇱",
    region: "Asia",
    support: "csca",
  },
  {
    code: "TR",
    name: "Turkey",
    flag: "🇹🇷",
    region: "Asia/Europe",
    support: "csca",
  },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", region: "Asia", support: "csca" },
  { code: "UG", name: "Uganda", flag: "🇺🇬", region: "Africa", support: "csca" },
  {
    code: "UY",
    name: "Uruguay",
    flag: "🇺🇾",
    region: "South America",
    support: "csca",
  },
  {
    code: "VA",
    name: "Vatican City",
    flag: "🇻🇦",
    region: "Europe",
    support: "csca",
  },
  {
    code: "VC",
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    region: "Caribbean",
    support: "csca",
  },
  {
    code: "VE",
    name: "Venezuela",
    flag: "🇻🇪",
    region: "South America",
    support: "csca",
  },
  {
    code: "ZW",
    name: "Zimbabwe",
    flag: "🇿🇼",
    region: "Africa",
    support: "csca",
  },

  // Special Territories and Organizations
  {
    code: "UN",
    name: "United Nations Laissez-Passer",
    flag: "🇺🇳",
    region: "International",
    support: "special",
  },
  {
    code: "ZZ",
    name: "Unknown/Test Documents",
    flag: "❓",
    region: "Special",
    support: "special",
  },
];

export const getCountryByCode = (code: string): Country | undefined =>
  countries.find((country) => country.code === code);

export const searchCountries = (query: string): Country[] => {
  const lowerQuery = query.toLowerCase();
  return countries.filter(
    (country) =>
      country.name.toLowerCase().includes(lowerQuery) ||
      country.code.toLowerCase().includes(lowerQuery) ||
      country.region.toLowerCase().includes(lowerQuery)
  );
};
